# Server configuration for all profiles
server:
  port: 8080
  servlet:
    context-path: /twitter-clone

# Spring configuration for all profiles
spring:
  application:
    name: TwitterCloneService
  datasource:
    driver-class-name: org.postgresql.Driver
  hikari:
    connectionTimeout: 20000
    maximum-pool-size: 5
  jpa:
    database: POSTGRESQL
    show-sql: true

springdoc:
  api-docs:
    version: OpenAPI 3.0
---
#local
spring:
  config:
    active:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/twitter-clone
    username: clowiesilubrico@gmail.com
    password: root

#---
#dev configuration
#spring:
#  config:
#    active:
#      on-profile: dev
#  datasource:
#    url: jdbc:postgresql://localhost:5432/practice_app_one_dev
#    username: postgresDev
#    password: rootDev

#---
#staging configuration
#spring:
#  profiles:
#    active: staging
#  datasource:
#    url: jdbc:postgresql://localhost:5432/practice_app_one_staging
#    username: postgresStaging
#    password: rootStaging

#---
#prod
#spring:
#  profiles:
#    active: prod
#  datasource:
#    url: jdbc:postgresql://localhost:5432/practice_app_one_prod
#    username: postgresProd
#    password: rootProd